#!/bin/bash

# Make an image collage out of a URL
# https://github.com/raphaelbastide/website-poster

# Number of folder level to search in
search_depth=1
# Images extentions to look for
extentions=jpg,gif,png,svg

read -p "Use natural image sizes? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]; then
  naturalsize=1
fi
echo -e "\nEnter a URL: "
read url
# mkdir ./images
rm ./images/*
rm poster.png
wget -nd -r -l $search_depth -P images -A $extentions $url

if (( $naturalsize == 1 ));
then
  echo -e "\n Proceeding to collage…"
  montage images/* -mode Concatenate -tile 7x -background white poster.png
else
  echo -e "\n Proceeding to collage…"
  montage images/* -tile 7x -geometry 200x200+50+50 -background white poster.png
fi
echo "Your Poster is ready!"
